from __future__ import annotations

import hashlib
import json
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .gltf_skin_analysis import GlbContainer, GltfSkinAnalysisError, has_skinned_mesh_primitives, read_glb_container
from .humanoid_quality_gate import HumanoidQualityGateError, run_humanoid_quality_gate
from .semantic_body_graph import SemanticBodyReport, build_semantic_body_report
from .semantic_humanoid_resolver import SemanticHumanoidResolutionError, resolve_humanoid


class HumanoidResolutionFailure(ValueError):
    def __init__(self, message: str, diagnostics: list[dict[str, Any]] | None = None) -> None:
        super().__init__(message)
        self.diagnostics = diagnostics or []


@dataclass(frozen=True)
class ResolvedHumanoidSource:
    kind: str
    payload: dict[str, Any]
    provenance: dict[str, Any]
    warnings: list[dict[str, str]]


@dataclass(frozen=True)
class HumanoidEvidenceProbe:
    status: str
    kind: str | None
    path: str
    diagnostics: list[dict[str, Any]]


UNVERIFIED_TRUSTED_SOURCE_WARNING = {
    "code": "trusted_humanoid_source_unverified",
    "message": "Explicit humanoid_source was trusted as caller-provided metadata, but no embedded skin-weight quality-gate evidence was available; do not treat this as independently certified safe humanoid retargeting.",
    "severity": "warning",
}


def resolve_humanoid_source(output_path: Path) -> ResolvedHumanoidSource:
    container = _try_read_glb_container(output_path)
    companion = output_path.with_name(f"{output_path.stem}.humanoid.json")
    if companion.exists():
        payload = _read_json_file(companion, source_kind="companion")
        semantic_report = _semantic_report_for(container, payload)
        quality_gate = _quality_gate_diagnostic(container, payload, semantic_report=semantic_report)
        provenance = {
            "source_kind": "companion",
            "path": str(companion),
            "payload_sha256": _hash_payload(payload),
        }
        if quality_gate is not None:
            provenance["quality_gate"] = quality_gate
        return ResolvedHumanoidSource(
            kind="companion",
            payload=payload,
            provenance=provenance,
            warnings=[],
        )

    glb_json = container.json if container is not None else _read_glb_json(output_path)
    extras = glb_json.get("extras") if isinstance(glb_json, dict) else None
    declared = extras.get("unirig_humanoid") if isinstance(extras, dict) else None
    if declared is not None:
        if not isinstance(declared, dict):
            raise HumanoidResolutionFailure(
                "GLB extras source extras.unirig_humanoid must be a JSON object. "
                "Provide a valid companion .humanoid.json or repair the retained extras metadata."
            )
        semantic_report = _semantic_report_for(container, declared)
        quality_gate = _quality_gate_diagnostic(container, declared, semantic_report=semantic_report)
        provenance = {
            "source_kind": "glb_extras",
            "path": str(output_path),
            "json_pointer": "/extras/unirig_humanoid",
            "payload_sha256": _hash_payload(declared),
        }
        if quality_gate is not None:
            provenance["quality_gate"] = quality_gate
        return ResolvedHumanoidSource(
            kind="glb_extras",
            payload=declared,
            provenance=provenance,
            warnings=[],
        )

    try:
        payload = resolve_humanoid(glb_json)
    except SemanticHumanoidResolutionError as exc:
        raise HumanoidResolutionFailure(str(exc), diagnostics=exc.diagnostics) from exc
    semantic_report = _semantic_report_for(container, payload)
    quality_gate = _quality_gate_diagnostic(container, payload, semantic_report=semantic_report)
    provenance = {
        "source_kind": "semantic_resolver",
        "path": str(output_path),
        "method": payload.get("provenance", {}).get("method", ""),
        "payload_sha256": _hash_payload(payload),
    }
    if quality_gate is not None:
        provenance["quality_gate"] = quality_gate
    return ResolvedHumanoidSource(
        kind="semantic_resolver",
        payload=payload,
        provenance=provenance,
        warnings=[
            {
                "code": "humanoid_source_from_semantic_resolver",
                "message": "Humanoid metadata was generated by semantic graph/rest/symmetry resolution, not exact bone-count profile dispatch.",
                "severity": "warning",
            }
        ],
    )


def probe_humanoid_evidence(path: Path) -> HumanoidEvidenceProbe:
    try:
        resolved = resolve_humanoid_source(path)
    except HumanoidResolutionFailure as exc:
        return HumanoidEvidenceProbe(status="failed", kind=None, path=str(path), diagnostics=list(exc.diagnostics))
    return HumanoidEvidenceProbe(status="resolved", kind=resolved.kind, path=str(path), diagnostics=[])


def resolve_explicit_humanoid_source(output_path: Path, humanoid_source: dict[str, Any]) -> ResolvedHumanoidSource:
    container = _try_read_glb_container(output_path)
    semantic_report = _semantic_report_for(container, humanoid_source)
    quality_gate = _quality_gate_diagnostic(container, humanoid_source, semantic_report=semantic_report)
    provenance: dict[str, Any] = {
        "source_kind": "provided",
        "method": "explicit-argument",
        "payload_sha256": _hash_payload(humanoid_source),
    }
    warnings: list[dict[str, str]] = []
    if quality_gate is None:
        provenance["quality_gate"] = {
            "code": "humanoid_rig_quality_gate",
            "status": "trusted_source_unverified",
            "reason": "embedded_skin_weight_evidence_not_available",
        }
        provenance["safe_retargeting_evidence"] = "unverified"
        warnings.append(dict(UNVERIFIED_TRUSTED_SOURCE_WARNING))
    else:
        provenance["quality_gate"] = quality_gate
        provenance["safe_retargeting_evidence"] = "quality_gate_passed" if quality_gate.get("status") == "passed" else "unverified"
    return ResolvedHumanoidSource(kind="provided", payload=humanoid_source, provenance=provenance, warnings=warnings)


def _try_read_glb_container(output_path: Path) -> GlbContainer | None:
    is_glb_container = _has_glb_magic(output_path)
    try:
        return read_glb_container(output_path)
    except (GltfSkinAnalysisError, OSError, json.JSONDecodeError) as exc:
        if is_glb_container:
            raise HumanoidResolutionFailure(json.dumps(_unsupported_glb_diagnostic(output_path, exc), sort_keys=True)) from exc
        return None


def _semantic_report_for(container: GlbContainer | None, payload: dict[str, Any]) -> SemanticBodyReport | None:
    if container is None or not has_skinned_mesh_primitives(container.json):
        return None
    try:
        return build_semantic_body_report(container, payload)
    except GltfSkinAnalysisError:
        return None


def _quality_gate_diagnostic(container: GlbContainer | None, payload: dict[str, Any], *, semantic_report: SemanticBodyReport | None = None) -> dict[str, Any] | None:
    if container is None:
        return None
    try:
        report = run_humanoid_quality_gate(container, payload, semantic_report=semantic_report)
    except HumanoidQualityGateError as exc:
        raise HumanoidResolutionFailure(json.dumps(exc.diagnostic, sort_keys=True)) from exc
    if report.status == "not_applicable":
        return None
    return report.diagnostic


def _has_glb_magic(output_path: Path) -> bool:
    try:
        with output_path.open("rb") as handle:
            return handle.read(4) == b"glTF"
    except OSError:
        return False


def _unsupported_glb_diagnostic(output_path: Path, exc: BaseException) -> dict[str, Any]:
    return {
        "code": "unsafe_for_humanoid_retarget",
        "severity": "error",
        "reasons": [
            {
                "code": "unsupported_glb_container",
                "message": f"Embedded GLB could not be parsed for humanoid quality-gate evidence: {exc}",
                "path": str(output_path),
            }
        ],
        "joint_classes": {},
        "weight_summary": {"vertex_count": 0},
        "weighted_joints": {},
        "remediation": "Export a valid embedded glTF 2.0 GLB with readable JSON/BIN chunks and skin-weight accessors, or avoid metadata_mode=humanoid.",
    }


def _read_json_file(path: Path, *, source_kind: str) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise HumanoidResolutionFailure(f"{source_kind} humanoid source is not valid JSON: {path}; {exc}") from exc
    if not isinstance(payload, dict):
        raise HumanoidResolutionFailure(f"{source_kind} humanoid source must be a JSON object: {path}")
    return payload


def _read_glb_json(output_path: Path) -> dict[str, Any]:
    data = output_path.read_bytes()
    if len(data) < 20 or data[:4] != b"glTF":
        return {}
    json_length = struct.unpack_from("<I", data, 12)[0]
    chunk_type = data[16:20]
    if chunk_type != b"JSON":
        return {}
    raw_json = data[20 : 20 + json_length].rstrip(b" \t\r\n\x00")
    payload = json.loads(raw_json.decode("utf-8"))
    return payload if isinstance(payload, dict) else {}


def _hash_payload(payload: dict[str, Any]) -> str:
    canonical = json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()
